export const LOGIN_START = 'LOGIN/START';
export const LOGIN_CLEAR = 'LOGIN/CLEAR';
export const LOGIN_SESSION = 'LOGIN/SESSION';
export const LOGIN_REQUEST = 'LOGIN/REQUEST';
export const LOGIN_SUCCESS = 'LOGIN/SUCCESS';
export const LOGIN_FAILURE = 'LOGIN/FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT/REQUEST';
